declare module "react-native-vector-icons/AntDesign"
declare module "react-native-vector-icons/MaterialIcons"
declare module "react-native-vector-icons/Fontisto"
declare module "react-native-vector-icons/Ionicons"
declare module "react-native-vector-icons/MaterialCommunityIcons"
declare module "react-native-vector-icons/EvilIcons"